### ISSUE TITLE
How scala Set distinguish two different objects?

### ISSUE THREAD

**Issue by jxw1102** [jxw1102/Projet-merou#3]
In my code, each CaseStmt will be connected to the CompoundStmt(accolade) of SwitchStmt. If i use **scala.collection.mutable.Set** as the type of **_prev** and **_next**, 
```private val _next = MSet[SourceCodeNode]()```
```private val _prev = MSet[SourceCodeNode]()```
there is one CaseStmt that is not connected to CompoundStmt; *CompoundStmt.next = List(DefaultStmt_102871548, CaseStmt_102871358)*

![set](https://cloud.githubusercontent.com/assets/1309108/6093238/6c69f0dc-aefe-11e4-82f6-9175325ce929.png)

if i use **scala.collection.mutable.ArrayBuffer** as the type of  **_prev** and **_next**, 
```private val _next = ArrayBuffer[SourceCodeNode]()```
```private val _prev = ArrayBuffer[SourceCodeNode]()```
i can get the expected result.     *CompoundStmt.next = List(CaseStmt_102871358, CaseStmt_102871420, DefaultStmt_102871548)*

![array](https://cloud.githubusercontent.com/assets/1309108/6093239/6eaf1980-aefe-11e4-9ce3-69b86463f667.png)

**Comment by Dicee** [comment]
I think the best approach is the Set because you will probably have to remove some nodes in your graph to produce the final graph, and for removal, a Set is by far more efficient than an ArrayBuffer (linear data structure). Moreover, you have some duplicate links in your second graph.

However, I also have some issues (using Set) and I am beginning to think the Set does not work in Scala as in Java. I'm not willing to do it right now but if you do, you can explore the following options : 

- overriding equals and hashCode, probably basing them on the id of the Stmt
- remember that >> and << operators change the states of the mutable Set in **both ways**. It might be a problem if you are iterating over the set while calling these operators. In the case of the ArrayBuffer, which is ordered, it would cause no harm whereas a HashSet has no defined order. It's just a vague guess, but you can try using a LinkedHashSet.

**Comment by jxw1102** [comment]
Yes, it's more reasonable to use Set. I overrided ```equals``` and ```hashCode``` like this. Now the Set works!
![screen shot 2015-02-07 at 20 12 00](https://cloud.githubusercontent.com/assets/1309108/6093590/afc452c6-af05-11e4-9c8a-42a548901062.png)

**Comment by Dicee** [comment]
Just another remark : it might be safer to call a constructor to instantiate the sets rather than the apply method on the Set object, because this way you cannot be sure of what kind of set you will be using

**Comment by Dicee** [comment]
Also, your implementation of hashCode and equals rises some problems in a more general context, but it is partly due to our poor design (id as an Option). For equals, you should return false if the type is not compatible before casting.
